login_logout
shinonome-inc/backend-final-assignment-i-mak33-124 pull request #2
Opened 2023-02-22 06:30 UTC by i-mak33-124

login,logout機能を実装しました。
レビューをお願い致します。
![キャプチャw](https://user-images.githubusercontent.com/119940942/220541098-bc64002c-e8b6-48d0-8157-785906586baf.PNG)

2023-02-22 16:23 UTC, gw31415 requested changes
全体的によく書けていると思います！

いくつかコメントさせていただきます。

2023-02-25 14:51 UTC, Akinori13 requested changes
よく書けています！少しだけコメントしました！
- ログアウトボタンを実装しましょう

2023-02-26 03:26 UTC, Akinori13 requested changes
コメントしました！！
- 他の人のコードは見て構いませんから、きちんと動くことと理解することを大切にしましょう！

2023-02-26 10:33 UTC, Akinori13 requested changes
あと少しです！修正したら想定通りの実装になっているか画面で確認しましょう

2023-02-26 12:13 UTC, merged