Tweet
shinonome-inc/backend-final-assignment-i-mak33-124 pull request #3
Opened 2023-02-26 14:31 UTC by i-mak33-124

ツイート機能を実装しました。
レビューをよろしくお願い致します。

2023-03-01 00:04 UTC, sui-false requested changes

2023-03-04 16:22 UTC, sui-false commented
今のままではtweetをadminから確認できないので、確認できるように修正しましょう

2023-03-04 16:23 UTC, sui-false requested changes

2023-03-04 16:23 UTC, sui-false commented on templates/accounts/profile.html
> +                <p>{{ tweet.id }}</p>
tweet.idは別になくても問題ないかと思います。

2023-03-04 16:23 UTC, sui-false commented on tweets/models.py
> +    created_time_date = models.DateTimeField(auto_now_add=True)  # モデルの保存時に時刻・日付を保存
created_atの方が短く、分かりやすいので変更してしまいましょう

2023-03-04 16:23 UTC, sui-false commented on templates/tweets/detail.html
> +            <p>投稿者:{{tweet.user}}</p>
ここからprofileに飛べるとなおよいと思います！

2023-03-11 17:55 UTC, sui-false requested changes

2023-03-11 17:55 UTC, sui-false commented on tweets/views.py
> +class HomeView(LoginRequiredMixin, ListView):  # 必ず先頭に
このままではN＋1問題が起きてしまっているので、直しましょう！
下の記事が参考になるかもしれません。
https://blog.shinonome.io/sql-django-n-plus-1/

2023-03-12 01:49 UTC, sui-false approved these changes

2023-03-12 05:58 UTC, Akinori13 approved these changes
LGTM

2023-03-12 06:01 UTC, merged